### ISSUE TITLE
Maui Blazor - Microsoft.JSInterop.JSException: this.cropperInstance.destroy is not a function

### ISSUE THREAD

**Issue by dimplevador** [CropperBlazor/Cropper.Blazor#113]
Hi, 

We are using Cropper.Blazor in Hybrid Maui Blazor app. 

The destroy method of Cropper is invoked even on pages where we do not use Cropper.Blazor. That in itself is fine but on those pages cropperInstance has not been initialized, hence Maui throws this error:

> this.cropperInstance.destroy is not a function
> TypeError: this.cropperInstance.destroy is not a function
>     at CropperDecorator.destroy (https://0.0.0.0/_content/Cropper.Blazor/cropperJsInterop.min.js:1:186)
>     at https://0.0.0.0/_framework/blazor.webview.js:1:3337
>     at new Promise (<anonymous>)
>     at beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3311)
>     at https://0.0.0.0/_framework/blazor.webview.js:1:42795
>     at EventTarget.<anonymous> (<anonymous>:7:62)
>     at EventTarget.i (https://0.0.0.0/dist/scripts/index.js:2:164733)
>     at EmbeddedBrowserWebView.<anonymous> (<anonymous>:1:38156)
>     at EmbeddedBrowserWebView.i (https://0.0.0.0/dist/scripts/index.js:2:164733)

I am new to Maui and do not know what is the proper solution for this. Should all methods in CropperDecorator check if the cropperInstance is initialized or should we add a dummy destroy method to the uninitialized cropperInstance or there is something wrong with MAUI and it should not have triggered the destroy method of Cropper at all?????

Please help.

Thank you!

**Comment by MaxymGorn** [comment]
I think, this example MAUI projects for .NET 7 version can help you: https://github.com/CropperBlazor/Cropper.Blazor/tree/dev/examples/Cropper.Blazor.MAUI.Net7

In addition, if you can still investigation all functionality cropper, just check that files:
- https://github.com/CropperBlazor/Cropper.Blazor/blob/dev/src/Cropper.Blazor/Client/Pages/CropperDemo.razor.cs
-

**Comment by dimplevador** [comment]
> I think, this example MAUI projects for .NET 7 version can help you: https://github.com/CropperBlazor/Cropper.Blazor/tree/dev/examples/Cropper.Blazor.MAUI.Net7
> 
> In addition, if you can still investigation all functionality cropper from [demo site](https://cropperblazor.github.io/demo), just check these files:
> 
> * https://github.com/CropperBlazor/Cropper.Blazor/blob/dev/src/Cropper.Blazor/Client/Pages/CropperDemo.razor.cs
> * https://github.com/CropperBlazor/Cropper.Blazor/blob/dev/src/Cropper.Blazor/Client/Pages/CropperDemo.razor

@MaxymGorn Thank you very much for replying! I tried out the examples you mentioned. It didn't help. The error was still thrown. After digging around the source code, I found that using ICropperJsInterop as a service in CropperComponent.razor.cs was causing the problem. That service was outliving all other components of the app. Don't ask me why, I have no idea.

If I remove ICropperJsInterop as a service in CropperComponent.razor.cs and instead use it as a normal instance, everything works just fine.

**So, the changes in CropperComponent.razor.cs**
Instead of `[Inject] ICropperJsInterop CropperJsIntertop { get; set; } = null!;`

We have:
```csharp
    [Inject] private IJSRuntime JsRuntime { get; set; } = null!;

    private ICropperJsInterop? CropperJsIntertop { get; set; } = null;
    
    protected override Task OnInitializedAsync()
    {
        if (CropperJsIntertop == null)
        {
            CropperJsIntertop = new CropperJsInterop(JsRuntime);    
        }
        
        return base.OnInitializedAsync();
    }
```
I also removed `builder.Services.AddCropper();` from MauiProgram.cs

I guess it will be better to implement IDisposable in CropperComponent.razor.cs and destroy CropperJsIntertop there.

What do you think?

**Comment by MaxymGorn** [comment]
Tought interesting, I'm guessing it might be a lifetime issue with the ICropperJsInterop service. Now we use that service as transient scope (I can add scope or singleton scope for that service)! Maybe better to get me example your code for better understanding that problem. I do not rule out that this may be a problem in MAUI itself!

Sorry, I didn't catch  means "That service was outliving all other components of the app."

**Comment by MaxymGorn** [comment]
You can verify if it is problem with lifetime with ICropperJsInterop service and used customs initialization `builder.Services.AddCropper();` like that:

`builder.Services.TryAddScoped<ICropperJsInterop, CropperJsInterop>();`

or 

`builder.Services.TryAddSingleton<ICropperJsInterop, CropperJsInterop>();`

or

`builder.Services.TryAddTransient<ICropperJsInterop, CropperJsInterop>();` (used now)

**Comment by dimplevador** [comment]
Testing it is easy. Just use the Cropper.Blazor in .Net 7 Maui hybrid Blazor app. The Cropper component should not be on home page. Make 3 pages in total.  (I should be able to give you a sample app during weekend, if you are not in a hurry).

Home page should open the 2nd page and the 2nd page should open the 3rd page which contains the component. 

Now start the app and navigate till the 2nd page. Don't go to the 3rd page containing the Cropper component. 

Press the back button. Now, you should see that error in the browser console. The "init" method of "cropperJsInterop.js" is never invoked. So "cropperInstance" in "CropperDecorator" is empty. Hence it throws error when Destroy method is invoked on it here: https://github.com/CropperBlazor/Cropper.Blazor/blob/db6efa79b7f18f0a7d511e4c59f14850b3d4aa8b/src/Cropper.Blazor/Cropper.Blazor/wwwroot/cropperJsInterop.js#L16

Now, this one: "That service was outliving all other components of the app." - sorry for the poor choice of words. This issue explains it better: [DisposeAsync() on IJSObjectReference causes hanging...](https://github.com/dotnet/maui/issues/13529) You were right, partially, it is also an issue of how Maui hybrid blazor is disposing components.

I have a question though, why make ICropperJsInterop as service at all? It isn't needed. Its lifetime should be tightly tied to the CropperComponent. It should be destroyed when that component is destroyed. Making it Singleton or Scoped will not do that. 

Honestly, I am very confused at the moment. I have debugged so much that I have now forgotten what I started debugging it for...

**Comment by MaxymGorn** [comment]
Hi @dimplevador. Ok, I will wait example app with this issues.

Regarding your question about ICropperJsInterop as service at all:

Now the ICropperJsInterop service for the cropper component works like this, for every new cropper there is a new ICropperJsInterop service, because it is configured with the Transient life scope, as ! I also made it as a service, as it will be reused elsewhere, including custom croppers, etc.

**Comment by dimplevador** [comment]
@MaxymGorn Ok! I'll send you the example app.

**Just my thoughts as an outsider (I could be totally wrong since I don't understand all the use cases for the lib):**
I still feel that ICropperJsInterop is not needed as a service. Making it transient is equal to declaring it in the component itself. When using it in custom croppers, won't it be better to make it inheritable instead? Make custom croppers extend the main Cropper classes or components.

**Comment by dimplevador** [comment]
@MaxymGorn Sorry for the delay. Give me one more day. I got caught up in work. Few things moved up the priority list out of the blue and I had to take care of it.

**Comment by dimplevador** [comment]
@MaxymGorn Ok so, Maui hates me, it seems. I am not able to reproduce the original JsInterop error that I contacted you about in a fresh app with nothing but just Cropper.Blazor. Spent most part of my afternoon with it but... no dice. I suspect that I have forgotten the steps to reproduce the error or where to look for the error. I tried it with Cropper.Blazor 1.1.2 and also 1.1.3

But, I was able to reproduce the app freezing issue on splash screen i.e. "That service was outliving all other components of the app", which is the root cause for that JsInterop error. The one that I linked you to the other issue [DisposeAsync() on IJSObjectReference causes hanging...](https://github.com/dotnet/maui/issues/13529)

The test repo: 
[https://github.com/dimplevador/CropperTest.git](https://github.com/dimplevador/CropperTest.git)

What you need: 
1) Android device running on anything below Android 12. I tested on Android 8.1

Steps to reproduce: 
1) Start the test app.
2) On home page click on "Cropper-1" -> "Cropper-2" -> "Cropper demo page" -> You should be able to see the cropper component here.
3) Now press the phone's back button until you exit the app.
4) Go to the android app list and start the demo app. Do not start it from the IDE in debug mode. You have to start it from the app list in this step.
5) You will notice that the app freezes on splash screen infinitely. You will have to kill the app by removing it from phone's history and start it again for it to work.
6) To test that the CropperComponent is the one causing the issue, On home page click on "Cropper-1" -> "Cropper-2". Stop here.  Do not click on "Cropper demo page". Now press phone's back button until you exit the app. Start the app from the app list. The app will start just fine.

This issue is fixed if we make changes to the CropperComponent as I had mentioned [here](https://github.com/CropperBlazor/Cropper.Blazor/issues/113#issuecomment-1448643167) i.e. remove it as service. 
I have limited understanding of MAUI blazor. There might be some other solution to this, but I don't know about it.

Thank you for your patience in dealing with me :)

**Comment by dimplevador** [comment]
I tried the latest version 1.2 today. I was drowned in work, had to delay working with Cropper blazor. 
All the problems are resolved now! Thank you very much. Works great with .Net7
