### ISSUE TITLE
Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by ralfbalzer** [CropperBlazor/Cropper.Blazor#114]
I have my BlazorApp in a sub directory and when I run the Cropper, I get the following message:

`Failed to fetch dynamically imported module`

I found the same issue in another project:

[(https://github.com/ljbc1994/BlazorIntersectionObserver/issues/35)]

Maybe this could be addressed?
Thanks

**Comment by MaxymGorn** [comment]
I suppose, you doesn't imported js module in index.html:
`<script src="_content/Cropper.Blazor/cropper.js"></script>`

**Comment by MaxymGorn** [comment]
I'm sorry, seems we have mistakes in readme file regarding importing files, now we should use that link for import js module: 
`<script src="_content/Cropper.Blazor/cropper.min.js"></script>`

**Comment by MaxymGorn** [comment]
I hope I answered your question, let me know if this solved your problem, if not please give me more information about it!

**Comment by ralfbalzer** [comment]
@MaxymGorn thanks for the reply. No this does not solve the problem.

I have a MVC application that also has two Blazor apps within the same project. Therefore, the Balzor apps are in sub folders within the MVC app.

So my BlazorHub (for one app) is added like this:

`app.MapBlazorHub("/myApp/_blazor");`

and to import the js file, I have to add

`<base href="~/myApp/" />`  and
`<script src="~/_content/MudBlazor/MudBlazor.min.js"></script>` and
`<script src="~/_content/Cropper.Blazor/cropper.min.js"></script>`

However, when I run the Blazor app, the browser looks for the `_content` files in this location:

`myApp/_content/Cropper.Blazor/cropper.min.js`

To make it work, I have to create a folder und `wwwroot` like `wwwroot/myApp/_content` and copy the cropper files in there.
With two Blazor apps, I have to do this twice and am duplicating the files.

It would be better, if the files could default to be read from the baseUrl, as suggested in my original comment.

**Comment by MaxymGorn** [comment]
Okay, I will fix this issue and use that PR as example for resolve our problem: https://github.com/ljbc1994/BlazorIntersectionObserver/pull/36

@ralfbalzer I wanna ping when new version Nuget was deployed

**Comment by MaxymGorn** [comment]
@ralfbalzer Cropper.Blazor Nuget version 1.1.3 was deployed. You can also see example hybrid MVC with Blazor project: https://github.com/CropperBlazor/Cropper.Blazor/tree/dev/examples/Cropper.MVC.With.Blazor.Server.Net7

**Comment by MaxymGorn** [comment]
Okay, have a nice day and don't forget to star the project if you liked it!

**Comment by zimmer62** [comment]
I'm having this same issue still with version 1.2.0  The path is being stripped and then I get an error message: Error: Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://www.mydomain.com/_content/Cropper.Blazor/cropperJsInterop.min.js 

I'm using Blazor Server .NET 7 and publishing to an IIS server under an application which is not the root path.
e.g.
https://www.mydomain.com/myapplication/ 

Looking over the code, I'm not sure it's using the navigation manager properly.  The file in question is CropperJSInterop.cs

This code is still stripping away the /myapplication path, it's replacing the path and query with empty string.

```
public async Task LoadModuleAsync(CancellationToken cancellationToken = default)
        {
            Uri baseUri = new Uri(_navigationManager.BaseUri);
            string pathAndQuery = baseUri.PathAndQuery;
            string hostName = baseUri.ToString().Replace(pathAndQuery, string.Empty);
            string globalPathToCropperModule = Path.Combine(hostName, PathToCropperModule);

            Module = await _jsRuntime.InvokeAsync<IJSObjectReference>(
                "import", cancellationToken, globalPathToCropperModule);
        }
```

It seems this could be simplified, and fix my problem using the navigation manager's ToAbsoluteUri method, here is my solution:

```
    public async Task LoadModuleAsync(CancellationToken cancellationToken = default)
    {
        string globalPathToCropperModule = _navigationManager.ToAbsoluteUri(PathToCropperModule).AbsoluteUri;

        Module = await _jsRuntime.InvokeAsync<IJSObjectReference>(
            "import", cancellationToken, globalPathToCropperModule);
    }
```

Could this bug be opened back up to take a look at this once again?  Or should I submit a new bug?

**Comment by MaxymGorn** [comment]
After looking at the unit tests, I see that this functionality was quite unexpected:
<img width="863" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/1beff50f-8942-4d77-b73f-dbf8e8491efb">
