### ISSUE TITLE
Dynamically Change Image in Cropper Element

### ISSUE THREAD

**Issue by HasanAnsar** [CropperBlazor/Cropper.Blazor#150]
How I can dynamically change image in cropper element through components parameter?

**Comment by MaxymGorn** [comment]
You can see that functionality in demo site: https://cropperblazor.github.io/demo
<img width="839" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/525f7a56-7c5c-4db2-9140-fedb899b6c74">
Example code:
1) UI - https://github.com/CropperBlazor/Cropper.Blazor/blob/dev/src/Cropper.Blazor/Client/Pages/CropperDemo.razor#L130
<img width="446" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/c7771c08-e7c6-4341-8aa7-e064064caf81">

2) https://github.com/CropperBlazor/Cropper.Blazor/blob/dev/src/Cropper.Blazor/Client/Pages/CropperDemo.razor.cs#L327
<img width="511" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/b74ec6aa-26c7-4880-b205-efa37fb02fdd">

**Comment by HasanAnsar** [comment]
it's changing through Browse but i have url's of image that appears conditionally how to change image through URL not browsing

**Comment by MaxymGorn** [comment]
You can use replace function, for instance:
`await CropperComponent?.ReplaceAsync("your url", true);`

**Comment by HasanAnsar** [comment]
There is nothing Function like ReplaceAsync have you added it now?

**Comment by MaxymGorn** [comment]
It was already in the cropper service, but it was not added to the cropper component

**Comment by MaxymGorn** [comment]
You can use the new version of the package right now!

**Comment by MaxymGorn** [comment]
I'm sorry, but unfortunately, after replacing the image, the functions become dead for some reason, you need to find out what's going wrong

**Comment by MaxymGorn** [comment]
Hi @HasanAnsar . Now, in package version 1.2.2 it should work.

Example:
1) You need include "IsAvaibleInitCropper" property as true (default)
<img width="505" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/54ded48a-3ee5-4aaa-8b88-51ad9ab2f547">
2) When you wanna change image in cropper dynamically, you can use that method:
```
IsAvaibleInitCropper = false; // ReplaceAsync call on ready event, after that we have double initialization cropper, as result we need block that. You can unblock this property when it demand on for destroy and full re-creation component.
CropperComponent?.ReplaceAsync(src);
CropperComponent?.RevokeObjectUrlAsync(oldSrc);
```
In addition, if you use error handing code should likewise that:
```
                if (IsErrorLoadImage)
                {
                    IsAvaibleInitCropper = true;
                    IsErrorLoadImage = false;
                }
                else
                {
                    IsAvaibleInitCropper = false;
                }

                CropperComponent?.ReplaceAsync(src);
                CropperComponent?.RevokeObjectUrlAsync(oldSrc);
```

**Comment by MaxymGorn** [comment]
Hi @HasanAnsar . Now, in package version 1.2.2 it should work.

Example:
1) You need include "IsAvaibleInitCropper" property as true (default)
<img width="505" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/54ded48a-3ee5-4aaa-8b88-51ad9ab2f547">

2) When you wanna change image in cropper dynamically, you can use that method:
```
IsAvaibleInitCropper = false; // ReplaceAsync call on ready event, after that we have double initialization cropper, as result we need block that. You can unblock this property when it demand on for destroy and full re-creation component.
CropperComponent?.ReplaceAsync(src);
CropperComponent?.RevokeObjectUrlAsync(oldSrc);
```
In addition, if you use error handing code should likewise that:
```
                if (IsErrorLoadImage)
                {
                    IsAvaibleInitCropper = true;
                    IsErrorLoadImage = false;
                }
                else
                {
                    IsAvaibleInitCropper = false;
                }

                CropperComponent?.ReplaceAsync(src);
                CropperComponent?.RevokeObjectUrlAsync(oldSrc);
```

**Comment by Vian237** [comment]
I'm currently using version 1.2.4 and I still have the same problem. unlike your example, I receive the image url via an event and I'd like to replace it in the component. I've made the adjustments described above but the image is just replaced by the cropper box size. when I relaunch the component I get the real size of the image outside the component so it's impossible to work.

![code](https://github.com/CropperBlazor/Cropper.Blazor/assets/147245595/3f2494cc-5986-400d-aa78-510d54da5e9d)

**Comment by MaxymGorn** [comment]
Hi @Vian237. Sorry, I'm fuzzy underhand your expectations. Could you provide more details about result of work? Maybe you want to see a complete reload of the component with the image replaced and centered according to the image dimensions, right?

**Comment by MaxymGorn** [comment]
@Vian237 just try to use this functionality: https://github.com/CropperBlazor/Cropper.Blazor/blob/da58751ca88059c9c505bdff6b0c5a5262905f7f/src/Cropper.Blazor/Client/Pages/CropperDemo.razor.cs#L386
<img width="1280" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/a36bf2cf-7dcd-4242-8193-88156660b5a4">
Code: 
```
string oldSrc = Src;

                Src = await CropperComponent!.GetImageUsingStreamingAsync(imageFile, imageFile.Size);

                IsAvailableInitCropper = true;
                IsErrorLoadImage = false;

                CropperComponent?.Destroy();
                CropperComponent?.RevokeObjectUrlAsync(oldSrc);
```

**Comment by MaxymGorn** [comment]
@Vian237 let me know if it work properly with this case!

**Comment by Vian237** [comment]
Hi @MaxymGorn I tried it before I came across this thread. In my context I receive the image directly as a string and so I can't use the "GetImageUsingStreamingAsync" method because I don't have an HTLM <input> tag.

The problem I had with this code was that when the first image is received, the component behaves well, then when the 2nd is received, it displays all the images in a row. That's why I wanted to use the "Replace" method.

I think the "Destroy()" method doesn't work because maybe the image isn't updated in the component because I'm changing the source directly to the new image.

Here's what my code looks like:
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/147245595/8ced7f50-0d56-4640-932d-d1a163abed19)

**Comment by MaxymGorn** [comment]
@Vian237  Sure, the original src don't updated in case when you gathering replace image

**Comment by MaxymGorn** [comment]
Replace method shouldn't call Destroy method Blazor component

**Comment by MaxymGorn** [comment]
I would investigate this point, how to center the image after replacing...

**Comment by MaxymGorn** [comment]
> I'm currently using version 1.2.4 and I still have the same problem. unlike your example, I receive the image url via an event and I'd like to replace it in the component. I've made the adjustments described above but the image is just replaced by the cropper box size. when I relaunch the component I get the real size of the image outside the component so it's impossible to work. Could you help me?
> 
> ![image](https://user-images.githubusercontent.com/147245595/281376740-140fd30a-6e5e-4721-84b7-a445bb0ff8b9.png)

Simple decision in your case: 
<img width="601" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/ae7175af-56df-4ec2-83ef-bbcd6ca35937">
Just set not required (`hasSameSize`) parameter to `false`
