### ISSUE TITLE
Suggestions for making integrating easier

### ISSUE THREAD

**Issue by biegehydra** [CropperBlazor/Cropper.Blazor#169]
Great wrapper but I have a few suggestions.

- Make the `Preview` parameter on `Options` have a default value and create a `<CropperPreview>` component or something like that.
  - Let people configure the size of the preview on this component
- Provide a built in way to start editing an image from a url so I don't have to create an `IBrowserFile`
  - Simply setting the 'Src' didn't work for me. Maybe it works if the 'Src' is set when the component is initialized but that wasn't the case for me
- Do something about `cropper-container` and `img-container`.
  - The read.me uses `cropper-demo`. Your demo page uses `cropper-container`. It is shipped with the later. Ideally, `cropper-container` should be the default value and the Class parameter acts as a way to add classes.
  - `img-container` really ties the component together and should be should probably. Possibly `CropperContainer` though that causes confusion with the above css class.

Other than that, nice repo.

**Comment by MaxymGorn** [comment]
Hi @biegehydra . 

1. I suppose we can make `Preview `parameter in option like `string`, `HTMLElement` or `collection HTMLElement` when I see declaration types preview from original library: https://github.com/fengyuanchen/cropperjs/blob/main/types/index.d.ts#L147C11-L147C11
2. I see your PR and left small suggestions about that
3. I agree with this opinion

**Comment by MaxymGorn** [comment]
After investigation regarding `cropper-container` that uses in template cropper and doesn't allowed in existing version (1.5.13) library:
<img width="549" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/d43f7938-dd32-4904-9e36-3288a72dbb3e">
In this case NAMESPACE hard coded as "cropper"
<img width="421" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/1bde5ca7-aa31-48c2-81bd-25a47af7948d">

Is tough difference things in our demo

**Comment by MaxymGorn** [comment]
I'm really accidently used `cropper-container` in this place :)
<img width="1023" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/c7daedb9-9a11-4d55-8625-f7cc0a55263f">

**Comment by MaxymGorn** [comment]
Currently CropperPreview can use as ElementReference.

**Comment by MaxymGorn** [comment]
CropperPreview can also be used for the second version of cropper.js, which is still in the beta version stage

**Comment by biegehydra** [comment]
> 3. Try to use `Replace` method from the cropper component or re-create cropper-component. Example button in demo: 

That replaces with a "Blob Url". One in which the data of the image is encoded within the URL. My suggestion was to have a built in way to replace with an actual image url. Not a blob url.

**Comment by MaxymGorn** [comment]
@biegehydra  This method also works for normal http url images too if I understand you correctly. It would be great if you could provide me with some sample
