### ISSUE TITLE
Reset the image preview programmatically when image is removed.

### ISSUE THREAD

**Issue by saadsaeed01** [CropperBlazor/Cropper.Blazor#177]
Hi 
I have a case in which I am showing a live preview of the cropper using the `ElementReference` as highlighted in the image below. 

![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/3503cc82-a5ab-4cd9-883d-f73bade7d90d)

The preview and the cropper are located in two different components.  I have created a render fragment and passed the fragment to the component which I want the preview to be shown as given below:

```
  <Front BusinessCard="@_card" RefeshUI="@_refreshCardUI" DesignerDropzoneCanDrops="@_designerDropzoneCanDrops">
  <LogoImagePreviewRenderFragment>
  <div @ref="_logoImagePreviewReference" class="img-preview preview-logo ml-4 mt-1 mb-1"></div></LogoImagePreviewRenderFragment>
 <StripImagePreviewRenderFragment>
<div @ref="_stripImagePreviewReference" class="img-preview preview-strip mb-3 mt-1"></div></StripImagePreviewRenderFragment>
</Front>
```
I am using the same reference in the image cropper component as given below:
```
  protected override void OnAfterRender(bool firstRender)
        {
            if (firstRender && ImagePreviewReference.Context is not null)
            {
                Options.Preview = new ElementReference[]
                {
                   ImagePreviewReference
                };
            }
        }
```

I need to somehow programmatically clear the preview when I remove the image but the preview is still visible as shown in the image below. What I am doing wrong here?

![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/70eb9d06-c96d-48c2-aff6-cfb2d358132e)

**Note**
I have also tried using the API to **Destroy** and **Init** the cropper again. But, the problem remains.
```
  public void ResetCropper()
        {
            CropperComponent?.Destroy();
            CropperComponent?.RevokeObjectUrlAsync(ImageDetails.ActualImage);
            CropperComponent?.InitCropper();
        }
```

**Comment by MaxymGorn** [comment]
@saadsaeed01 Ok, can you provide the code data how you use these croppers, I have a sample where my croppers are compatible with each other, I can provide them in about 4 hours

**Comment by MaxymGorn** [comment]
@saadsaeed01 Is this error still relevant after the deployment of the new version of the package 1.2.4?
