### ISSUE TITLE
[Question]: Set Zoom for the cropper on initilization

### ISSUE THREAD

**Issue by saadsaeed01** [CropperBlazor/Cropper.Blazor#182]
Hi 

I have an issue that I wanted to discuss related to setting up the initial Zoom

Let's say when I upload the image the initial state of the cropper is this

![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/2461538c-3fc0-40bf-9ece-86bd0d120d15)

Now without **Zooming in** or **Zooming out**, I change the position of the **crop window** and save my entity
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/ac6ba8f8-e9a9-4b76-a7ad-73af003c6be9)

If I now save my **card** the position of the cropper window will persist. The image below shows the position of the cropper window when I save my card and visit the page again
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/fe44b856-1f84-4b77-a1e1-250e97a26212)

**Problem**
If I **Zoom out** or **Zoom In** in the cropper like this and save the **entity**
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/a0d74b86-38c8-4528-b772-95c5bee1f6a9)

The zoom is not persisted. **Check what happened below**
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/aa16d528-bc49-4892-8773-3ea1cb39052a)

I am saving the following Meta Information
- Height
- Width
- ScaleX
- ScaleY
- X
- Y
- Rotate
- OldRatio (Fetched from **OnZoomEvent)**
- Ratio (Fetched from **OnZoomEvent)**

On initializing the cropper, I set the non-zoom properties like this in **SetDataOptions**
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/e83ff155-cbcf-4acd-8d4e-e8f649f3a155)

And I set the zoom properties by calling the ZoomTo method
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/91fdee77-baa1-4c40-9942-60ce17a47e7a)

 Is there a special way to set the zoom of the canvas, unfortunately, I am not very clear about this. Waiting for your response

I am using Blazor Server NET 6 and the package version is 1.2.4 which is the **latest stable**

Thank you very much!

Regards
Saad

**Comment by MaxymGorn** [comment]
Hi @saadsaeed01. I suppose this option only available when the autoCrop option had set to the true, see official documentation: https://github.com/fengyuanchen/cropperjs#data

**Comment by saadsaeed01** [comment]
Hi @MaxymGorn 
I have set AutoCrop to true but this is not working. Please see the example 
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/066ab8d7-f10f-408d-87ba-09f4670e4bc2)

**Comment by MaxymGorn** [comment]
@saadsaeed01 You can try to use Zoom or ZoomTo, for example in OnCropReadyEvent
<img width="492" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/8654d599-6316-44df-8b22-3d9960569505">
<img width="422" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/9b7b5cbc-ea37-4fc7-b4a2-8405c796ab80">
I might that can help you!
And data on how much you need to zoom in or zoom out can be obtained from OnZoomEvent
<img width="409" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/69356607-3deb-48fc-89ea-f0943abc19e0">
<img width="671" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/d98c5929-e8d2-4991-870d-fd63aa35f7ad">

**Comment by saadsaeed01** [comment]
Hi @MaxymGorn 

Check out this solution, Hopefully, this will help other developers too. This is achieved using **OnReadyEvent**

![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/c84f0ae6-cdb9-4eff-b252-bf362a55b356)

Thank you for your valuable input :)

Regards
S
