### ISSUE TITLE
Zooming out in browser forces the image to disappear

### ISSUE THREAD

**Issue by saadsaeed01** [CropperBlazor/Cropper.Blazor#187]
**Description**
On certain width and height of the parent div in which the cropper component is placed, the image starts to get disappear.

**To Reproduce**
I am setting the **CanvasWidth (200px)** and **CanvasHeight(70px)** for the div in which the cropper is placed
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/bfd36341-3b9c-4061-a206-b171db4329c6)
If I zoom out the browser window the image starts to get disappear

Initial state
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/310a0d38-88ef-4997-841f-02b28172b4fd)

Zoom out (67%)
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/55914222-773d-4bd5-97b1-e33a2c011c6b)

**Expected behavior**
If I set **CanvasWidth (200px)** and  **CanvasHeight(100px)**, then this problem does not happen 
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/bfd36341-3b9c-4061-a206-b171db4329c6)

Zoom out (67%) {Note that image is not disappearing now}
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/04d3787f-6803-4514-acf1-9134d3a30caa)

What can be the possible reason behind this behavior? 

**Desktop**
 - OS: Windows 11 pro
 - Browser [Edge]
 - Version [115.0.1901.183]

**Comment by MaxymGorn** [comment]
Hi @saadsaeed01. Arguably this can help you: [https://github.com/fengyuanchen/cropperjs/issues/147](https://www.google.com/url?sa=i&source=web&cd=&ved=0CAIQw7AJahcKEwjgsrWHi7SAAxUAAAAAHQAAAAAQAg&url=https%3A%2F%2Fgithub.com%2Ffengyuanchen%2Fcropperjs%2Fissues%2F147&psig=AOvVaw3MKuqMw7wczVn6zprWDYfv&ust=1690725930224069&opi=89978449)

**Comment by MaxymGorn** [comment]
@saadsaeed01  To be honest, I don't know this aspect of the work from the original cropper.js library

**Comment by saadsaeed01** [comment]
HI @MaxymGorn 

This is not helping me to sort out this issue. Please see the video of what's happening over here.

https://www.loom.com/share/dca17ddfcb5f4b2285b37903d7a56792?sid=6895b4ba-8308-457f-9035-18cd3d50f1df

We needed to somehow intercept the zoom event if the cursor is not over the cropper and make sue it doesn't change the styles of the inner div elements  

Waiting for your response!
S

**Comment by MaxymGorn** [comment]
@saadsaeed01  Yes, I see your problem. I have the same one in an empty project, at the moment I don't know a clear reason why this happens! Maybe you need some styles for the cropper element or its container. It seems that there is no such problem on the demo cropper website, I am still trying to find out what could have caused this

**Comment by MaxymGorn** [comment]
In addition, I think it is worth writing about this problem in the cropper.js repository, most likely, the author of the library will know the answer. Repository cropper.js: https://github.com/fengyuanchen/cropperjs

**Comment by saadsaeed01** [comment]
Hi @MaxymGorn 

I have created a solution that works for me!
I have taken inspiration from this: https://github.com/fengyuanchen/cropperjs/issues/885#issuecomment-1091315068
Can you please check it out?

```
let timer
window.addEventListener('resize', () => {
    if (cropper == undefined) {
        return;
    }
    let keys = Object.keys(cropper.cropperInstances);
    clearTimeout(timer);
    keys.forEach((key) => {
        cropper.cropperInstances[key].disable();

    });
    timer = setTimeout(() => {
        let keys = Object.keys(cropper.cropperInstances);
        keys.forEach((key) => {
            cropper.cropperInstances[key].enable();

        });
    }, 100);
})
```

**Comment by MaxymGorn** [comment]
Hi @saadsaeed01. Great solution. I just some refactored this code and adding check when the cropper module is unloaded or there are no croppers at all:
```
let timer
window.addEventListener('resize', () => {
    if (!Object.hasOwn(this, 'cropper') || cropper == null || cropper.cropperInstances == null) {
        return;
    }
    let keys = Object.keys(cropper.cropperInstances);
    clearTimeout(timer);
    if (keys.length > 0) {
        keys.forEach((key) => {
            cropper.cropperInstances[key].disable();
        });
        timer = setTimeout(() => {
            let keys = Object.keys(cropper.cropperInstances);
            keys.forEach((key) => {
                cropper.cropperInstances[key].enable();
            });
        }, 100);
    }
})
```
