### ISSUE TITLE
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by saadsaeed01** [CropperBlazor/Cropper.Blazor#201]
**Description**
I am initializing Cropper with Blob URL's. I have set `CheckCrossOrigin` to false. When I call `GetCroppedCanvasDataURLAsync` method to get the cropped image, I get the following exception " Tainted canvases may not be exported"

**To Reproduce**
1. Set cross-origin to false
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/0b7406b0-ef65-4654-b1b2-0ed8577fee51)
2. Call `GetCroppedCanvasDataURLAsync` method to get the cropped image
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/33133831/e1042e9a-768c-4ea5-91f1-4aa7e6b4da31)
3. Following exception would be thrown
```
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at CropperDecorator.getCroppedCanvasDataURL (https://localhost:7066/_content/Cropper.Blazor/cropperJsInterop.min.js:1:1100)
    at https://localhost:7066/_framework/blazor.server.js:1:3501
    at new Promise (<anonymous>)
    at kt.beginInvokeJSFromDotNet (https://localhost:7066/_framework/blazor.server.js:1:3475)
    at https://localhost:7066/_framework/blazor.server.js:1:72077
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (https://localhost:7066/_framework/blazor.server.js:1:72063)
    at kt._processIncomingData (https://localhost:7066/_framework/blazor.server.js:1:70105)
    at connection.onreceive (https://localhost:7066/_framework/blazor.server.js:1:64508)
    at o.onmessage (https://localhost:7066/_framework/blazor.server.js:1:48842)
```

**Expected behavior**
I am expecting to get the cropped image

**Desktop**
 - OS: Windows 11 pro
 - Browser [Edge]
 - Version [115.0.1901.183]

**Additional context**
Please note that I am using **blob URL** as image src.

**Comment by MaxymGorn** [comment]
Hi @saadsaeed01. In this case you need additionally to set up input attributes, namely just add "crossOrigin" tag with "anonymous" value or any other valuestags depending on your case
<img width="421" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/ff0ec07d-8c08-4ad7-a20c-87970e4b8a7f">
<img width="439" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/35134b7d-cebd-41f7-aac4-777bd11f5934">

**Comment by MaxymGorn** [comment]
Moreover, I think this resources can be useful for more investigation in your case: https://github.com/fengyuanchen/cropperjs/issues/258, https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin
