### ISSUE TITLE
Persist CSS details/data for cropped image when tabs are switched using MudTab

### ISSUE THREAD

**Issue by JunaidSultan20** [CropperBlazor/Cropper.Blazor#208]
**Describe the bug**
After cropping the original image, the newly cropped image is displayed on the UI. However, when I switch between the tabs, the CSS details for the cropped image are reset to 0px. The data or details persist for the original tab where the image is cropped but are lost when the tab is switched. Also, can we send multiple CSS classes? If so, how can be they assigned either using an array or comma separated string.

**To Reproduce**
1. Upload the original image.
2. Select the desired area of the image and crop it.
3. Observe that the cropped image is correctly displayed in the UI.
4. Switch to another tab and observe the images are not displayed.
5. Now switch back to the original tab and observe that the cropped image is visible.

**Expected behavior**
The copped image should be displayed when tabs are switched, and the style and CSS details should persist. Whenever I switch the tabs the cropped image should persist/visible on all tabs.

**Screenshots**
![Tab1](https://github.com/CropperBlazor/Cropper.Blazor/assets/73248084/21e52a1a-8944-4a6c-9fca-6afe3bf4ed65)
![Tab2](https://github.com/CropperBlazor/Cropper.Blazor/assets/73248084/0a1fce8b-c6c1-4799-bf9c-ee863b405a61)

**Code Snippet**
`Options = new Options()
{
    AspectRatio = CropperWindowWidth / CropperWindowHeight,
    ViewMode = ViewMode.Vm0,
    CorrelationId = Guid.NewGuid().ToString(),
    Preview = PreviewClass,
    AutoCrop = true,
    DragMode = "move"
};`

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Edge]
 - Version [116.0.1938.69]

**Comment by MaxymGorn** [comment]
Hi @JunaidSultan20 . I you wanna persist image cropper preview after destroying cropper (case when you change tabs) you need get image from preview or using GetCroppedCanvasDataURLAsync method cropper component for saving image and use it
