### ISSUE TITLE
Zoom on crop box center - Question

### ISSUE THREAD

**Issue by nhwilly** [CropperBlazor/Cropper.Blazor#222]
Great library, thank you for making it.

I've got this working now and I'm down to a question that's a little hard for me.

My crop box is fixed and extends to the entire container.  The user selects what they want to crop by moving and zooming the image.  I'm using a `MudSlider` to do the zooming part.  

But since I'm using the `Zoom` method instead of the `ZoomTo` method, it is zooming on the center on the image, not the coordinates of the center of the crop box.

As a result, the image area under the crop box appears to move in the direction of the center of the image - and that makes perfect sense.

You can see that here - I've not moved the image, but I have moved the slider and the image shifts:
![Zoom-1](https://github.com/CropperBlazor/Cropper.Blazor/assets/7560842/416b8b0e-1b9d-415f-8528-d1a69f080e8a)

![Zoom-2](https://github.com/CropperBlazor/Cropper.Blazor/assets/7560842/45490bf9-4d14-4608-af2a-945cb5c68342)

So I think I should use the `ZoomTo` method and provide the coordinates by calculating where the center of the crop box falls on the image.  I believe if I can do that, the crosshairs in the center will stay centered as the image enlarges.

I just don't know which method calls to use to make that happen.  It must be a ratio of some kind between the crop box and the image, but I can't figure it out.  

Has anyone else done this - or does anyone have any pointers?

Thanks.

***
For the record, I have disabled `WheelZoom`.  I need to have a slider there for mobile and I could never get the slider and the OnZoomedEvent coordinated properly, so I just gave up.

**Comment by MaxymGorn** [comment]
Hi @nhwilly. I see your question! 

In original logic `ZoomTo` used for zoom the canvas (image wrapper) to an absolute ratio: https://github.com/fengyuanchen/cropperjs#zoomtoratio-pivot

But `Zoom` used  for Zoom the canvas (image wrapper) with a relative ratio: https://github.com/fengyuanchen/cropperjs#zoomratio

Comeback to your case you should to use ZoomTo with this parameters:
`CropperComponent?.ZoomTo(ratio, 0, 0);`
Moreover, oou can see example implementation in demo site: 
<img width="1030" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/3d9388e9-77f6-4654-8623-1bbb529bd004">
Code:
<img width="613" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/49f20e8d-a310-4417-a183-51f477a7d5fb">
<img width="484" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/4e0b3666-53ca-442a-b72d-299d7f779a5c">

**Comment by nhwilly** [comment]
Thanks for the quick response.  

I tried your example in the demo, and the crosshairs still shift a bit.

The image is going to shift around no matter what I do.

This is turning out to be more trouble than it's worth.   Everything else is running smoothly.  Thanks, again.

**Comment by MaxymGorn** [comment]
@nhwilly I wonder if you can try if it works the same in the original version of the library on their site:https://fengyuanchen.github.io/cropperjs/?

**Comment by nhwilly** [comment]
I'll try that. Thanks

**Comment by nhwilly** [comment]
Their demo works the same way, so this isn't something wrong with your library.  

In their case, the crop box stays in the viewing area in the same place relative to the image, which is expanding.

So it appears the crosshair is moving, but it's not.  The image is moving.

See below - I am centering the crosshair between his eyebrows and on each zoom, the crosshair stays there.
![Screenshot 2023-09-21 182715](https://github.com/CropperBlazor/Cropper.Blazor/assets/7560842/06b3f03f-0e79-49f8-b268-3b18eb823eec)
![Screenshot 2023-09-21 182642](https://github.com/CropperBlazor/Cropper.Blazor/assets/7560842/f54d7621-dd85-455f-96b5-2e5b165f96d7)
![Screenshot 2023-09-21 182655](https://github.com/CropperBlazor/Cropper.Blazor/assets/7560842/2db66de7-09e2-4b3e-b474-4db885b24b58)

You can see what I'm trying to achieve, but it may, in fact, not be possible, because the extent of the image, it can no longer shift around without scrolling out of the container.

I'm using Vm3 to fill the container so no background shows.

I don't want to impose on your time, so don't feel obligated to figure this out, when, like I mentioned, it might not be possible/practical.

**Comment by MaxymGorn** [comment]
@nhwilly I have alternatives solution, we can use `Scale` for this case, for example:
`CropperComponent?.Scale(<YourScaleValue> * PreviousScaleXValue, <YourScaleValue> * PreviousScaleYValue);`
PreviousScaleXValue, PreviousScaleYValue - paramters which come come from `OnCropEvent`, for example
<img width="493" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/f5509a82-2d7d-49eb-bfe8-da4aa298d04c">
<img width="479" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/de5fce75-d9ea-4c88-9b99-979b548e8489">
