### ISSUE TITLE
Want to add CODE_OF_CONDUCT.md  to your repo , assign me the task under Hacktoberfest

### ISSUE THREAD

**Issue by sb-decoder** [CropperBlazor/Cropper.Blazor#228]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Pull Request**
- [ ] I would like to do a Pull Request

**Comment by MaxymGorn** [comment]
@sb-decoder code of conduct already added to this repository!
