### ISSUE TITLE
Cropped image not set immediately after loading an image

### ISSUE THREAD

**Issue by cryo75** [CropperBlazor/Cropper.Blazor#296]
I am loading an image into the cropper, and I would like to use either the `OnReadEvent` or `OnLoadImageEvent` to immediately get the cropped image (the crop box is already available).

How can I set the cropped image immediately?

**Comment by cryo75** [comment]
Problem solved.

**Comment by MaxymGorn** [comment]
Hi @cryo75. . Great to have your problem resolved. In addition, you can see comprehensive examples in https://cropperblazor.github.io/examples/cropperusage#simple-usage
