### ISSUE TITLE
Rotation of Image extends image outside the boundary of the Canvas

### ISSUE THREAD

**Issue by sykesbPragmatics** [CropperBlazor/Cropper.Blazor#300]
I'm attempting to integrate the component into our application and the use case I have is to rotate the image 90 degrees, which works fine except that the newly rotated image extends above and below the Canvas.  Is there a way to make the canvas re-scale or update upon rotation?

Example:

1. Go to https://cropperblazor.github.io/demo
2. Click VM1 (View mode 1)
3. Click the rotate button twice (Results in rotate of 90 degrees clockwise)
4. Image extends above and below the Canvas, but it should shrink slightly to remain within the canvas window.

Initial
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/91490750/37961e8f-4c0e-4609-a6d9-59b96543d617)

Image extends past top and bottom of Canvas
![image](https://github.com/CropperBlazor/Cropper.Blazor/assets/91490750/8c872e02-5511-43ac-b4ad-646e6a4ef271)

**Comment by MaxymGorn** [comment]
Hi @sykesbPragmatics . I'll look this week more details about this case. Now, I'm suppose youcneed to choose 3 VM, for instance:![Screenshot_20240209_012355_Chrome.jpg](https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/b4327d0c-9a80-4c9d-b039-03f5ba9d78b8)

**Comment by sykesbPragmatics** [comment]
Researching further, this is a cropper.js issue that has been around for a while.  I was able to come up with a fix for my scenario:

ViewMode = ViewMode.Vm2;
Zoomable = true;  //Required, you apparently cannot switch this on and off without reset?

```
 cropperComponent.Rotate(90);
 //Max Zoom out
 cropperComponent.ZoomTo(0, 0, 0);

 var container = await cropperComponent.GetContainerDataAsync();
 var canvas = await cropperComponent.GetCanvasDataAsync();
 //Re-center
 cropperComponent.MoveTo((container.Width / 2) - (canvas.Width / 2), 0);
```

**Comment by MaxymGorn** [comment]
> Researching further, this is a cropper.js issue that has been around for a while.  I was able to come up with a fix for my scenario:
> 
> ViewMode = ViewMode.Vm2;
> Zoomable = true;  //Required, you apparently cannot switch this on and off without reset?
> 
> ```
>  cropperComponent.Rotate(90);
>  //Max Zoom out
>  cropperComponent.ZoomTo(0, 0, 0);
> 
>  var container = await cropperComponent.GetContainerDataAsync();
>  var canvas = await cropperComponent.GetCanvasDataAsync();
>  //Re-center
>  cropperComponent.MoveTo((container.Width / 2) - (canvas.Width / 2), 0);
> ```

Sure, you need reset cropper. Or set up these properties instantly before render cropper component or in OnInitialized override method. If cropper component is rendered and you need update cropper options, then re-initialize cropper component. In addition, you can save state cropper cropped canvas and so and use Options.SetDataOptions method for change the cropped area position and size with new data (based on the original image). See more about this topic in this conversation: https://github.com/CropperBlazor/Cropper.Blazor/issues/182
