### ISSUE TITLE
change copper src image old image 

### ISSUE THREAD

**Issue by LeeCY-C** [CropperBlazor/Cropper.Blazor#309]
**Describe the bug**
![Uploading 8d4df8b72b62900b1e1c55786d41bcd.png…]()

load default image and first change image is no  problem.
The problem arise when change the image second time .
Change copper src image old image ,but old image append under the new image.
This problem will not always arise,It just happens sometimes.

**Comment by MaxymGorn** [comment]
Hi @LeeCY-C, I can't see the image you provided. Can you provide an image of the attachment with the problem and a possible code example In addition, this image is work in demo site: https://cropperblazor.github.io/demo?

**Comment by MaxymGorn** [comment]
Hi @LeeCY-C just use 'Replace' or 'Change' functionality: https://cropperblazor.github.io/examples/replacing#simple-usage, https://cropperblazor.github.io/examples/rebuild#simple-usage. In addition, you can see example of code from demo site: https://github.com/CropperBlazor/Cropper.Blazor/blob/68dfc6d6cb4043dc8f7c5ade6ec492dbf22974bd/src/Cropper.Blazor/Client/Pages/CropperDemo.razor.cs#L386, https://github.com/CropperBlazor/Cropper.Blazor/blob/68dfc6d6cb4043dc8f7c5ade6ec492dbf22974bd/src/Cropper.Blazor/Client/Pages/CropperDemo.razor.cs#L404

**Comment by LeeCY-C** [comment]
<img width="1112" alt="8d4df8b72b62900b1e1c55786d41bcd" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/70256381/611a8dd6-ad90-4e17-b1b8-f0b2267a167c"> this is the bug image

**Comment by LeeCY-C** [comment]
This is my code.
`        public async Task FileInputValueChanged(IBrowserFile imageFile)
        {
            try
            {
                if (imageFile != null)
                {
                    string oldSrc = imageSrc;
                    string newSrc = await ImageCropper!.GetImageUsingStreamingAsync(imageFile, imageFile.Size);

                    if (IsErrorLoadImage)
                    {
                        IsAvailableInitCropper = true;
                        IsErrorLoadImage = false;
                    }
                    else
                    {
                        IsAvailableInitCropper = false;
                    }

                    await Task.WhenAll(
                        ImageCropper?.ReplaceAsync(newSrc, false).AsTask(),
                        ImageCropper?.RevokeObjectUrlAsync(oldSrc).AsTask())
                        .ContinueWith(x =>
                        {
                            imageSrc = newSrc;
                        });
                }
            }
            catch (Exception exception)
            {
                await JSRuntime!.InvokeVoidAsync("console.log", $"{exception.Message}");
            }
        }`

**Comment by LeeCY-C** [comment]
This is my change image code.
`        public async Task FileInputValueChanged(IBrowserFile imageFile)
        {
            try
            {
                if (imageFile != null)
                {
                    string oldSrc = imageSrc;
                    string newSrc = await ImageCropper!.GetImageUsingStreamingAsync(imageFile, imageFile.Size);

                    if (IsErrorLoadImage)
                    {
                        IsAvailableInitCropper = true;
                        IsErrorLoadImage = false;
                    }
                    else
                    {
                        IsAvailableInitCropper = false;
                    }

                    await Task.WhenAll(
                        ImageCropper?.ReplaceAsync(newSrc, false).AsTask(),
                        ImageCropper?.RevokeObjectUrlAsync(oldSrc).AsTask())
                        .ContinueWith(x =>
                        {
                            imageSrc = newSrc;
                        });
                }
            }
            catch (Exception exception)
            {
                await JSRuntime!.InvokeVoidAsync("console.log", $"{exception.Message}");
            }
        }`

**Comment by MaxymGorn** [comment]
@LeeCY-C I memorize in old versions library we have that issue. Could you check your version of library or try to update and use newest version? In addition, could you provide temporary project with reproduce of bug to check it? Moreover, verify cropper component parameters: IsAvailableInitCropper, IsErrorLoadImage and so on...

**Comment by MaxymGorn** [comment]
Moreover, in your case we expecting to double initialization of cropper component, but we expect that regarding specific of work cropper component  in our docs
![Screenshot_20240311_234453_Chrome](https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/2859990b-64e3-4575-bbe3-225234fc7957)
You can governance of cropper lifestyle independently,  just using destroy or init function of cropper, but it should works in newest version of library properly.

**Comment by LeeCY-C** [comment]
[CopperTestFor#309.zip](https://github.com/CropperBlazor/Cropper.Blazor/files/14566184/CopperTestFor.309.zip)
This is an temporary project, and can recurrent this bug.

**Comment by MaxymGorn** [comment]
Hi @LeeCY-C in your case you should set up `IsAvailableInitCropper = false;` due to cropper.js rebuild inner cropper when you passed `hasSameSize` with `false `value in `ReplaceAsync` method.
<img width="669" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/60f795c5-e08a-4b8e-b98e-53e922959a25">
Seems we have this condition in our associated docs page, but you don't use error handing: 
<img width="772" alt="image" src="https://github.com/CropperBlazor/Cropper.Blazor/assets/50423072/3dd96117-bf8a-4285-959b-002b74c8d7b9">

**Comment by MaxymGorn** [comment]
@LeeCY-C but sometimes I have the same error for specific images, I have no clue in this moment why it's happened, I suppose it's a problem with hybrid WebView in WPF. I'm would investigate about this issue and multiple platforms. In your case, I'm recommended try to use rebuild cropper functionality: https://cropperblazor.github.io/examples/rebuild#simple-usage. 

Code:
public async Task FileInputValueChanged(IBrowserFile imageFile)
```
{
    try
    {
        if (imageFile != null)
        {
            string oldSrc = imageSrc;
            imageSrc = await ImageCropper!.GetImageUsingStreamingAsync(imageFile, imageFile.Size);

            IsAvailableInitCropper = true;
            IsErrorLoadImage = false;

            ImageCropper!.Destroy();
            ImageCropper!.RevokeObjectUrlAsync(oldSrc);
        }
    }
    catch (Exception exception)
    {
        _snackbarOptions.Content = exception.Message;
        PopupService!.EnqueueSnackbarAsync(_snackbarOptions);
    }
}
```

**Comment by LeeCY-C** [comment]
Thank you for your patient guidance. Now it work well.
