### ISSUE TITLE
multiple image viewer

### ISSUE THREAD

**Issue by man-chi** [CropperBlazor/Cropper.Blazor#387]
**Is your feature request related to a problem? Please describe.**
I am building image viewer to browser AI assisted generated images. I am amazing by the functionality of Cropper.Blazor open source. thanks for the hard work. but I need to display all the images in multiple viewer mode. is it possible on Cropper.blazor? pls help

**Describe the solution you'd like**
auto generate multiple images panel like a browser in blazor.

**Describe alternatives you've considered**
may be trying another content manager system to manager digital asset 

**Additional context**

**Pull Request**
- [ ] I would like to do a Pull Request

**Comment by MaxymGorn** [comment]
@man-chi  So, what is the problem with using different list options with own viewing modes for each croppers? Example of multiple croppers in a page: https://cropperblazor.github.io/examples/cropperusage#simple-usage
